// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1ErbnUArJwXQGQYxYrxpKDn8oY-7h7Sc',
    appId: '1:477118913211:web:b50be7d82446e7f39e679e',
    messagingSenderId: '477118913211',
    projectId: 'spyfall-5ae8d',
    authDomain: 'spyfall-5ae8d.firebaseapp.com',
    storageBucket: 'spyfall-5ae8d.firebasestorage.app',
    measurementId: 'G-BP8S5Q1C4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxVMa-PoyczWzgA5oiwGOk203bHwR9aKc',
    appId: '1:477118913211:android:272ee0e4fb5bb6049e679e',
    messagingSenderId: '477118913211',
    projectId: 'spyfall-5ae8d',
    storageBucket: 'spyfall-5ae8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSFNgPQ7xWJQ38vPgZBVfaWuHGI1JiUXo',
    appId: '1:477118913211:ios:df989e17db7e9edd9e679e',
    messagingSenderId: '477118913211',
    projectId: 'spyfall-5ae8d',
    storageBucket: 'spyfall-5ae8d.firebasestorage.app',
    iosBundleId: 'com.jeshwinprince.spyfall',
  );

}